/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
/**
 *
 * @author vhung
 */
import DAO.DAO_TacGia;
import DAO.DAO_NhaXuatBan;
import Model.Model_NhaXuatBan;
import Model.Model_TacGia;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class GUI_Home extends javax.swing.JFrame {
    ArrayList<Model_TacGia> danhsachTacGia;
    ArrayList<Model_NhaXuatBan> danhsachNhaXuatBan;
    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    

    private static void setSelectedIndex(int index) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form Home
     */
    public GUI_Home() {
        initComponents();
        loadbangtacgia();
        loadbangnhaxuatban();
        
        TableHienThiTacGia.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            // Lấy chỉ số hàng được chọn
            int selectedRow_TacGia = TableHienThiTacGia.getSelectedRow();

            // Lấy dữ liệu từ hàng được chọn và hiển thị lên các JTextField
            txt_maTacGia.setText(TableHienThiTacGia.getValueAt(selectedRow_TacGia, 0).toString());
            txt_tenTacGia.setText(TableHienThiTacGia.getValueAt(selectedRow_TacGia, 1).toString());
            txt_namSinh.setText(TableHienThiTacGia.getValueAt(selectedRow_TacGia, 2).toString());
            txt_namMat.setText(TableHienThiTacGia.getValueAt(selectedRow_TacGia, 3).toString());
            txt_quocTich.setText(TableHienThiTacGia.getValueAt(selectedRow_TacGia, 4).toString());
             }
            }
        );
        TableHienThiNhaXuatBan.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    // Lấy chỉ số hàng được chọn
                    int selectedRow = TableHienThiNhaXuatBan.getSelectedRow();

                    // Lấy dữ liệu từ hàng được chọn và hiển thị lên các JTextField
                    txt_maNhaXuatBan.setText(TableHienThiNhaXuatBan.getValueAt(selectedRow, 0).toString());
                    txt_tenNhaXuatBan.setText(TableHienThiNhaXuatBan.getValueAt(selectedRow, 1).toString());
                    txt_diaChi.setText(TableHienThiNhaXuatBan.getValueAt(selectedRow, 2).toString());
                    txt_soDienThoai.setText(TableHienThiNhaXuatBan.getValueAt(selectedRow, 3).toString());
                    txt_email.setText(TableHienThiNhaXuatBan.getValueAt(selectedRow, 4).toString());
                }
             }
         );
    }
    
    
    private void loadbangtacgia() {
        
    DefaultTableModel model = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return true; // Cho phép chỉnh sửa ô
        }
    };

    Object[] title = {"Mã tác giả", "Tên tác giả", "Năm sinh", "Năm mất", "Quốc tịch"};
    model.setColumnIdentifiers(title);

    danhsachTacGia = new DAO.DAO_TacGia().layDanhSachTacGia();
    for (Model_TacGia tg : danhsachTacGia) {
        Object[] row = {tg.getMaTacGia(), tg.getTenTacGia(), tg.getNamSinh(), tg.getNamMat(), tg.getQuocTich()};
        model.addRow(row);    
    }
    
    TableHienThiTacGia.setModel(model);
}
    private void loadbangnhaxuatban() {
        
    DefaultTableModel model = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return true; // Cho phép chỉnh sửa ô
        }
    };

    Object[] title = {"Mã nhà xuất bản", "Tên nhà xuất bản", "Địa chỉ", "Số điện thoại", "Email"};
    model.setColumnIdentifiers(title);

    danhsachNhaXuatBan = new DAO.DAO_NhaXuatBan().layDanhSachNhaXuatBan();
    for (Model_NhaXuatBan nxb : danhsachNhaXuatBan) {
        Object[] row = {nxb.getMaNhaXuatBan(), nxb.getTenNhaXuatBan(), nxb.getDiaChi(), nxb.getSoDienThoai(), nxb.getEmail()};
        model.addRow(row);    
    }
    
    TableHienThiNhaXuatBan.setModel(model);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        Home = new javax.swing.JTabbedPane();
        QL_NhaXuatBan = new javax.swing.JPanel();
        btn_Sua_NhaXuatBan = new javax.swing.JButton();
        jScrollPane_NhaXuatBan = new javax.swing.JScrollPane();
        TableHienThiNhaXuatBan = new javax.swing.JTable();
        btn_Reset_NhaXuatBan = new javax.swing.JButton();
        btn_Them_NhaXuatBan = new javax.swing.JButton();
        btn_Xoa_NhaXuatBan = new javax.swing.JButton();
        jPanel_Sua = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        txt_maNhaXuatBan = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txt_tenNhaXuatBan = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txt_diaChi = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txt_soDienThoai = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        them_txt_email = new javax.swing.JTextField();
        them_txt_tenNhaXuatBan = new javax.swing.JTextField();
        them_txt_diaChi = new javax.swing.JTextField();
        them_txt_soDienThoai = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        QL_TacGia = new javax.swing.JPanel();
        btn_Sua_TacGia = new javax.swing.JButton();
        jScrollPane_TacGia = new javax.swing.JScrollPane();
        TableHienThiTacGia = new javax.swing.JTable();
        btn_Reset_TacGia = new javax.swing.JButton();
        btn_Them_TacGia = new javax.swing.JButton();
        btn_Xoa_TacGia = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_maTacGia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_tenTacGia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_namSinh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_namMat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_quocTich = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        them_txt_quocTich = new javax.swing.JTextField();
        them_txt_tenTacGia = new javax.swing.JTextField();
        them_txt_namSinh = new javax.swing.JTextField();
        them_txt_namMat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ChucNang = new javax.swing.JPanel();
        btn_QuanLyTacGia = new javax.swing.JButton();
        btnQuanLyNhaXuatBan = new javax.swing.JButton();
        btnQuanLySach = new javax.swing.JButton();
        btnQuanLyMuon = new javax.swing.JButton();
        btnQuanLyDatSach = new javax.swing.JButton();
        btnDanhSachPhat = new javax.swing.JButton();
        btnQuanLyTaiKhoan = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Sua_NhaXuatBan.setText("Sửa");
        btn_Sua_NhaXuatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Sua_NhaXuatBanActionPerformed(evt);
            }
        });

        TableHienThiNhaXuatBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_NhaXuatBan.setViewportView(TableHienThiNhaXuatBan);

        btn_Reset_NhaXuatBan.setText("Làm mới");
        btn_Reset_NhaXuatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Reset_NhaXuatBanActionPerformed(evt);
            }
        });

        btn_Them_NhaXuatBan.setText("Thêm");
        btn_Them_NhaXuatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Them_NhaXuatBanActionPerformed(evt);
            }
        });

        btn_Xoa_NhaXuatBan.setText("Xóa");
        btn_Xoa_NhaXuatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Xoa_NhaXuatBanActionPerformed(evt);
            }
        });

        jLabel29.setText("Mã NXB");

        txt_maNhaXuatBan.setEditable(false);
        txt_maNhaXuatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maNhaXuatBanActionPerformed(evt);
            }
        });

        jLabel30.setText("Tên NXB");

        jLabel31.setText("Địa chỉ");

        jLabel32.setText("SĐT");

        txt_soDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soDienThoaiActionPerformed(evt);
            }
        });

        jLabel33.setText("Email");

        javax.swing.GroupLayout jPanel_SuaLayout = new javax.swing.GroupLayout(jPanel_Sua);
        jPanel_Sua.setLayout(jPanel_SuaLayout);
        jPanel_SuaLayout.setHorizontalGroup(
            jPanel_SuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SuaLayout.createSequentialGroup()
                .addGroup(jPanel_SuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_SuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_tenNhaXuatBan, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(txt_maNhaXuatBan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_diaChi)
                    .addComponent(txt_soDienThoai)
                    .addComponent(txt_email))
                .addContainerGap())
        );
        jPanel_SuaLayout.setVerticalGroup(
            jPanel_SuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SuaLayout.createSequentialGroup()
                .addGroup(jPanel_SuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_maNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel_SuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tenNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel_SuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel_SuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel_SuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel34.setText("Email");

        jLabel35.setText("SĐT");

        jLabel36.setText("Địa chỉ");

        jLabel37.setText("Tên NXB");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(them_txt_soDienThoai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(them_txt_diaChi, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(them_txt_tenNhaXuatBan, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(them_txt_email))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(them_txt_tenNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(them_txt_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(them_txt_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(them_txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout QL_NhaXuatBanLayout = new javax.swing.GroupLayout(QL_NhaXuatBan);
        QL_NhaXuatBan.setLayout(QL_NhaXuatBanLayout);
        QL_NhaXuatBanLayout.setHorizontalGroup(
            QL_NhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QL_NhaXuatBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_NhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(QL_NhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(QL_NhaXuatBanLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btn_Them_NhaXuatBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Sua_NhaXuatBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Xoa_NhaXuatBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Reset_NhaXuatBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(QL_NhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(QL_NhaXuatBanLayout.createSequentialGroup()
                    .addGap(666, 666, 666)
                    .addComponent(jPanel_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(34, Short.MAX_VALUE)))
        );
        QL_NhaXuatBanLayout.setVerticalGroup(
            QL_NhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QL_NhaXuatBanLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(QL_NhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(QL_NhaXuatBanLayout.createSequentialGroup()
                        .addComponent(jScrollPane_NhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(QL_NhaXuatBanLayout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Them_NhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Sua_NhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Xoa_NhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Reset_NhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195))))
            .addGroup(QL_NhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(QL_NhaXuatBanLayout.createSequentialGroup()
                    .addGap(279, 279, 279)
                    .addComponent(jPanel_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(371, Short.MAX_VALUE)))
        );

        Home.addTab("Quản lý sách", QL_NhaXuatBan);

        btn_Sua_TacGia.setText("Sửa");
        btn_Sua_TacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Sua_TacGiaActionPerformed(evt);
            }
        });

        TableHienThiTacGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_TacGia.setViewportView(TableHienThiTacGia);

        btn_Reset_TacGia.setText("Làm mới");
        btn_Reset_TacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Reset_TacGiaActionPerformed(evt);
            }
        });

        btn_Them_TacGia.setText("Thêm");
        btn_Them_TacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Them_TacGiaActionPerformed(evt);
            }
        });

        btn_Xoa_TacGia.setText("Xóa");
        btn_Xoa_TacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Xoa_TacGiaActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(5, 2));

        jLabel3.setText("Mã tác giả");
        jPanel1.add(jLabel3);

        txt_maTacGia.setEditable(false);
        txt_maTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maTacGiaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_maTacGia);

        jLabel4.setText("Tên tác giả");
        jPanel1.add(jLabel4);
        jPanel1.add(txt_tenTacGia);

        jLabel5.setText("Năm sinh");
        jPanel1.add(jLabel5);
        jPanel1.add(txt_namSinh);

        jLabel6.setText("Năm mất");
        jPanel1.add(jLabel6);
        jPanel1.add(txt_namMat);

        jLabel7.setText("Quốc tịch");
        jPanel1.add(jLabel7);
        jPanel1.add(txt_quocTich);

        jLabel9.setText("Quốc tịch");

        jLabel10.setText("Năm mất");

        jLabel11.setText("Năm sinh");

        jLabel12.setText("Tên tác giả");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(them_txt_namMat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(them_txt_namSinh, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(them_txt_tenTacGia, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(them_txt_quocTich))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(them_txt_tenTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(them_txt_namSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(them_txt_namMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(them_txt_quocTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout QL_TacGiaLayout = new javax.swing.GroupLayout(QL_TacGia);
        QL_TacGia.setLayout(QL_TacGiaLayout);
        QL_TacGiaLayout.setHorizontalGroup(
            QL_TacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QL_TacGiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(QL_TacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(QL_TacGiaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btn_Them_TacGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Sua_TacGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Xoa_TacGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Reset_TacGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        QL_TacGiaLayout.setVerticalGroup(
            QL_TacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QL_TacGiaLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(QL_TacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(QL_TacGiaLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Them_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Sua_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Xoa_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Reset_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Home.addTab("tab2", QL_TacGia);

        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, -36, 930, 840));

        ChucNang.setLayout(new java.awt.GridLayout(0, 1));

        btn_QuanLyTacGia.setText("Quản lý tác giả");
        btn_QuanLyTacGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_QuanLyTacGiaMouseClicked(evt);
            }
        });
        btn_QuanLyTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLyTacGiaActionPerformed(evt);
            }
        });
        ChucNang.add(btn_QuanLyTacGia);

        btnQuanLyNhaXuatBan.setText("Quản lý nhà xuất bản");
        btnQuanLyNhaXuatBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanLyNhaXuatBanMouseClicked(evt);
            }
        });
        btnQuanLyNhaXuatBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyNhaXuatBanActionPerformed(evt);
            }
        });
        ChucNang.add(btnQuanLyNhaXuatBan);

        btnQuanLySach.setText("Quản lý sách");
        btnQuanLySach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanLySachMouseClicked(evt);
            }
        });
        ChucNang.add(btnQuanLySach);

        btnQuanLyMuon.setText("Quản lý mượn");
        ChucNang.add(btnQuanLyMuon);

        btnQuanLyDatSach.setText("Danh sách đặt sách");
        ChucNang.add(btnQuanLyDatSach);

        btnDanhSachPhat.setText("Danh sách phạt");
        ChucNang.add(btnDanhSachPhat);

        btnQuanLyTaiKhoan.setText("Quản lý tài khoản");
        ChucNang.add(btnQuanLyTaiKhoan);

        getContentPane().add(ChucNang, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 81, 180, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_QuanLyTacGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyTacGiaMouseClicked
            // TODO add your handling code here:
    }//GEN-LAST:event_btn_QuanLyTacGiaMouseClicked

    private void btnQuanLySachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLySachMouseClicked
                  
    }//GEN-LAST:event_btnQuanLySachMouseClicked

    private void btnQuanLyNhaXuatBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanLyNhaXuatBanMouseClicked
        int index = Home.indexOfComponent(QL_NhaXuatBan);
            Home.setSelectedIndex(index);// 
    }//GEN-LAST:event_btnQuanLyNhaXuatBanMouseClicked

    private void btn_QuanLyTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLyTacGiaActionPerformed
         int index = Home.indexOfComponent(QL_TacGia);
            Home.setSelectedIndex(index);//    
    }//GEN-LAST:event_btn_QuanLyTacGiaActionPerformed

    private void btn_Them_TacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Them_TacGiaActionPerformed
        try {
        // Giả sử bạn có các JTextField cho các trường dữ liệu tương ứng

        String tenTacGia = them_txt_tenTacGia.getText();
        int namSinh = Integer.parseInt(them_txt_namSinh.getText());
        int namMat = Integer.parseInt(them_txt_namMat.getText());
        String quocTich = them_txt_quocTich.getText();

        Model_TacGia tg = new Model_TacGia();
        tg.setTenTacGia(tenTacGia);
        tg.setNamSinh(namSinh);
        tg.setNamMat(namMat);
        tg.setQuocTich(quocTich);

        DAO_TacGia dao = new DAO_TacGia();
        boolean isInserted = dao.insertTacGia(tg);
        
        // Trả về rỗng
        them_txt_tenTacGia.setText(""); 
        them_txt_namSinh.setText(""); 
        them_txt_namMat.setText(""); 
        them_txt_quocTich.setText(""); 
        
        if (isInserted) {
            JOptionPane.showMessageDialog(this, "Thêm tác giả thành công!");
            // Cập nhật lại bảng hiển thị nếu cần thiết
            loadbangtacgia();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm tác giả thất bại!");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_Them_TacGiaActionPerformed

    private void txt_maTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maTacGiaActionPerformed

    private void btn_Xoa_TacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Xoa_TacGiaActionPerformed
           int selectedRow = TableHienThiTacGia.getSelectedRow();

            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xóa.", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Lấy thông tin từ hàng được chọn
            int maTacGia = (int) TableHienThiTacGia.getValueAt(selectedRow, 0);
            String tenTacGia = (String) TableHienThiTacGia.getValueAt(selectedRow, 1); // Ví dụ lấy tên tác giả để hiển thị trong hộp thoại xác nhận

            // Hiển thị hộp thoại xác nhận
            int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa tác giả \"" + tenTacGia + "\" không?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                // Xóa tác giả từ CSDL
                boolean deleted = DAO.DAO_TacGia.deleteTacGia(maTacGia);

                if (deleted) {
                    JOptionPane.showMessageDialog(this, "Xóa tác giả thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    // Cập nhật lại bảng hiển thị sau khi xóa
                    loadbangtacgia();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa tác giả thất bại.", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            }
    }//GEN-LAST:event_btn_Xoa_TacGiaActionPerformed

    private void btn_Reset_TacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Reset_TacGiaActionPerformed
        txt_maTacGia.setText(""); 
        txt_tenTacGia.setText(""); 
        txt_namSinh.setText(""); 
        txt_namMat.setText(""); 
        txt_quocTich.setText(""); 
        
        them_txt_tenTacGia.setText(""); 
        them_txt_namSinh.setText(""); 
        them_txt_namMat.setText(""); 
        them_txt_quocTich.setText(""); 
        
        loadbangtacgia();
    }//GEN-LAST:event_btn_Reset_TacGiaActionPerformed

    private void btn_Sua_TacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Sua_TacGiaActionPerformed
            // Lấy dữ liệu từ các JTextField
            int maTacGia = Integer.parseInt(txt_maTacGia.getText());
            String tenTacGia = txt_tenTacGia.getText();
            int namSinh = Integer.parseInt(txt_namSinh.getText());
            int namMat = Integer.parseInt(txt_namMat.getText());
            String quocTich = txt_quocTich.getText();

            // Kiểm tra xem có sự thay đổi so với dữ liệu ban đầu hay không
            boolean changed_TacGia = checkChanges_TacGia(maTacGia, tenTacGia, namSinh, namMat, quocTich);

            if (!changed_TacGia) {
                JOptionPane.showMessageDialog(this, "Không có thay đổi cần cập nhật.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            // Gọi phương thức update của DAO_TacGia để cập nhật thông tin tác giả
            boolean updated_TacGia = DAO.DAO_TacGia.updateTacGia( maTacGia, tenTacGia, namSinh, namMat, quocTich);
            if (updated_TacGia) {
                // Thông báo cập nhật thành công
                JOptionPane.showMessageDialog(this, "Đã cập nhật thông tin tác giả thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

                // Sau khi cập nhật thành công, cập nhật lại bảng hiển thị
                loadbangtacgia();
            } else {
                // Thông báo cập nhật không thành công
                JOptionPane.showMessageDialog(this, "Có lỗi xảy ra trong quá trình cập nhật thông tin tác giả.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }

        // Phương thức kiểm tra sự thay đổi so với dữ liệu ban đầu
        private boolean checkChanges_TacGia(int maTacGia, String tenTacGia, int namSinh, int namMat, String quocTich) {
            // Lấy dữ liệu từ JTable để so sánh
            int selectedRow = TableHienThiTacGia.getSelectedRow();
            int maTacGiaInTable = (int) TableHienThiTacGia.getValueAt(selectedRow, 0);
            String tenTacGiaInTable = (String) TableHienThiTacGia.getValueAt(selectedRow, 1);
            int namSinhInTable = (int) TableHienThiTacGia.getValueAt(selectedRow, 2);
            int namMatInTable = (int) TableHienThiTacGia.getValueAt(selectedRow, 3);
            String quocTichInTable = (String) TableHienThiTacGia.getValueAt(selectedRow, 4);

            txt_maTacGia.setText(""); 
            txt_tenTacGia.setText(""); 
            txt_namSinh.setText(""); 
            txt_namMat.setText(""); 
            txt_quocTich.setText(""); 
            // So sánh các giá trị
            if (maTacGia != maTacGiaInTable ||
                !tenTacGia.equals(tenTacGiaInTable) ||
                namSinh != namSinhInTable ||
                namMat != namMatInTable ||
                !quocTich.equals(quocTichInTable)) {
                return true; // Có sự thay đổi
            }

            return false; // Không có sự thay đổi
            
            
    }//GEN-LAST:event_btn_Sua_TacGiaActionPerformed

    private void btn_Sua_NhaXuatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Sua_NhaXuatBanActionPerformed
        // Lấy dữ liệu từ các JTextField
            int maNhaXuatBan = Integer.parseInt(txt_maNhaXuatBan.getText());
            String tenNhaXuatBan = txt_tenNhaXuatBan.getText();
            String diaChi = txt_diaChi.getText();
            String soDienThoai = txt_soDienThoai.getText();
            String email = txt_email.getText();

            // Kiểm tra xem có sự thay đổi so với dữ liệu ban đầu hay không
            boolean changed = checkChanges_NhaXuatBan(maNhaXuatBan, tenNhaXuatBan, diaChi, soDienThoai, email);

            if (!changed) {
                JOptionPane.showMessageDialog(this, "Không có thay đổi cần cập nhật.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            // Gọi phương thức update của DAO_NhaXuatBan để cập nhật thông tin tác giả
            boolean updated = DAO.DAO_NhaXuatBan.updateNhaXuatBan( maNhaXuatBan, tenNhaXuatBan, diaChi, soDienThoai, email);
            if (updated) {
                // Thông báo cập nhật thành công
                JOptionPane.showMessageDialog(this, "Đã cập nhật thông tin nhà xuất bản thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

                // Sau khi cập nhật thành công, cập nhật lại bảng hiển thị
                loadbangnhaxuatban();
            } else {
                // Thông báo cập nhật không thành công
                JOptionPane.showMessageDialog(this, "Có lỗi xảy ra trong quá trình cập nhật thông tin nhà xuất bản.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btn_Sua_NhaXuatBanActionPerformed
        private boolean checkChanges_NhaXuatBan(int maNhaXuatBan, String tenNhaXuatBan, String diaChi, String soDienThoai, String email) {
                    // Lấy dữ liệu từ JTable để so sánh
                    int selectedRow = TableHienThiNhaXuatBan.getSelectedRow();
                    int maNhaXuatBanInTable = (int) TableHienThiNhaXuatBan.getValueAt(selectedRow, 0);
                    String tenTacGiaInTable = (String) TableHienThiNhaXuatBan.getValueAt(selectedRow, 1);
                    String DiaChiTable = (String) TableHienThiNhaXuatBan.getValueAt(selectedRow, 2);
                    String soDienThoaiInTable = (String) TableHienThiNhaXuatBan.getValueAt(selectedRow, 3);
                    String emailInTable = (String) TableHienThiNhaXuatBan.getValueAt(selectedRow, 4);

                    txt_maNhaXuatBan.setText(""); 
                    txt_tenNhaXuatBan.setText(""); 
                    txt_diaChi.setText(""); 
                    txt_soDienThoai.setText(""); 
                    txt_email.setText(""); 
                    // So sánh các giá trị
                    if (maNhaXuatBan != maNhaXuatBanInTable ||
                        !tenNhaXuatBan.equals(tenTacGiaInTable) ||
                        diaChi != DiaChiTable ||
                        soDienThoai != soDienThoaiInTable ||
                        !email.equals(emailInTable)) {
                        return true; // Có sự thay đổi
                    }

                    return false; // Không có sự thay đổi


            }           
    private void btn_Reset_NhaXuatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Reset_NhaXuatBanActionPerformed
        txt_maNhaXuatBan.setText(""); 
        txt_tenNhaXuatBan.setText(""); 
        txt_diaChi.setText(""); 
        txt_soDienThoai.setText(""); 
        txt_email.setText(""); 
        
        them_txt_tenNhaXuatBan.setText(""); 
        them_txt_diaChi.setText(""); 
        them_txt_soDienThoai.setText(""); 
        them_txt_email.setText(""); 
        
        loadbangnhaxuatban();
    }//GEN-LAST:event_btn_Reset_NhaXuatBanActionPerformed

    private void btn_Them_NhaXuatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Them_NhaXuatBanActionPerformed
            try {
            // Giả sử bạn có các JTextField cho các trường dữ liệu tương ứng

            String tenNhaXuatBan= them_txt_tenNhaXuatBan.getText();
            String diaChi = them_txt_diaChi.getText();
            String soDienThoai = them_txt_soDienThoai.getText();
            String Email = them_txt_email.getText();

            Model_NhaXuatBan nxb = new Model_NhaXuatBan();
            nxb.setTenNhaXuatBan(tenNhaXuatBan);
            nxb.setDiaChi(diaChi);
            nxb.setSoDienThoai(soDienThoai);
            nxb.setEmail(Email);

            DAO_NhaXuatBan dao = new DAO_NhaXuatBan();
            boolean isInserted = dao.insertNhaXuatBan(nxb);

            // Trả về rỗng
            them_txt_tenNhaXuatBan.setText(""); 
            them_txt_diaChi.setText(""); 
            them_txt_soDienThoai.setText(""); 
            them_txt_email.setText(""); 

            if (isInserted) {
                JOptionPane.showMessageDialog(this, "Thêm nhà xuất bản thành công!");
                // Cập nhật lại bảng hiển thị nếu cần thiết
                loadbangnhaxuatban();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm nhà xuất bản thất bại!");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_Them_NhaXuatBanActionPerformed

    private void btn_Xoa_NhaXuatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Xoa_NhaXuatBanActionPerformed
        int selectedRow = TableHienThiNhaXuatBan.getSelectedRow();

            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xóa.", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Lấy thông tin từ hàng được chọn
            int maNhaXuatBan = (int) TableHienThiNhaXuatBan.getValueAt(selectedRow, 0);
            String tenNhaXuatBan = (String) TableHienThiNhaXuatBan.getValueAt(selectedRow, 1); // Ví dụ lấy tên tác giả để hiển thị trong hộp thoại xác nhận

            // Hiển thị hộp thoại xác nhận
            int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa nhà xuất bản \"" + tenNhaXuatBan + "\" không?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                // Xóa nhà xuất bản từ CSDL
                boolean deleted = DAO.DAO_NhaXuatBan.deleteNhaXuatBan(maNhaXuatBan);

                if (deleted) {
                    JOptionPane.showMessageDialog(this, "Xóa nhà xuất bản thành công.", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    // Cập nhật lại bảng hiển thị sau khi xóa
                    loadbangnhaxuatban();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa tác giả thất bại.", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            }
    }//GEN-LAST:event_btn_Xoa_NhaXuatBanActionPerformed

    private void txt_maNhaXuatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maNhaXuatBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maNhaXuatBanActionPerformed

    private void btnQuanLyNhaXuatBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyNhaXuatBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanLyNhaXuatBanActionPerformed

    private void txt_soDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soDienThoaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChucNang;
    private javax.swing.JTabbedPane Home;
    private javax.swing.JPanel QL_NhaXuatBan;
    private javax.swing.JPanel QL_TacGia;
    private javax.swing.JTable TableHienThiNhaXuatBan;
    private javax.swing.JTable TableHienThiTacGia;
    private javax.swing.JButton btnDanhSachPhat;
    private javax.swing.JButton btnQuanLyDatSach;
    private javax.swing.JButton btnQuanLyMuon;
    private javax.swing.JButton btnQuanLyNhaXuatBan;
    private javax.swing.JButton btnQuanLySach;
    private javax.swing.JButton btnQuanLyTaiKhoan;
    private javax.swing.JButton btn_QuanLyTacGia;
    private javax.swing.JButton btn_Reset_NhaXuatBan;
    private javax.swing.JButton btn_Reset_TacGia;
    private javax.swing.JButton btn_Sua_NhaXuatBan;
    private javax.swing.JButton btn_Sua_TacGia;
    private javax.swing.JButton btn_Them_NhaXuatBan;
    private javax.swing.JButton btn_Them_TacGia;
    private javax.swing.JButton btn_Xoa_NhaXuatBan;
    private javax.swing.JButton btn_Xoa_TacGia;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel_Sua;
    private javax.swing.JScrollPane jScrollPane_NhaXuatBan;
    private javax.swing.JScrollPane jScrollPane_TacGia;
    private javax.swing.JTextField them_txt_diaChi;
    private javax.swing.JTextField them_txt_email;
    private javax.swing.JTextField them_txt_namMat;
    private javax.swing.JTextField them_txt_namSinh;
    private javax.swing.JTextField them_txt_quocTich;
    private javax.swing.JTextField them_txt_soDienThoai;
    private javax.swing.JTextField them_txt_tenNhaXuatBan;
    private javax.swing.JTextField them_txt_tenTacGia;
    private javax.swing.JTextField txt_diaChi;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_maNhaXuatBan;
    private javax.swing.JTextField txt_maTacGia;
    private javax.swing.JTextField txt_namMat;
    private javax.swing.JTextField txt_namSinh;
    private javax.swing.JTextField txt_quocTich;
    private javax.swing.JTextField txt_soDienThoai;
    private javax.swing.JTextField txt_tenNhaXuatBan;
    private javax.swing.JTextField txt_tenTacGia;
    // End of variables declaration//GEN-END:variables
}
